spring.application.name=FermeDirecte

# Database MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/FermeDirecte?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Server
server.servlet.context-path=/api
server.port=8081
server.servlet.encoding.charset=UTF-8

# Logging
logging.level.com.FermeDirecte=debug

# JWT
jwt.secret=bXlTdXBlclNlY3JldEtleUZlcm1lRGlyZWN0ZTIwMjZTZWN1cmVCYXNlNjRLZXk=
jwt.expiration=900000
jwt.refresh-expiration=604800000

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
